### ISSUE TITLE
Out of town

### ISSUE THREAD

**Issue by szlkiev** [PAC-ROM/pac-rom#1]
Guys, currently I'm out of town for my job project, unfortunately it will be for couple of months, 3-4 months maybe.
I only bring my netbook with me which of course it's not sufficient for compiling a ROM.
So in the time being i might can't  make updates or fixes, because i can't test it, therefore i ask for all of you guys who ever capable to make a contribution by updating & fixing bugs encountered.
I'll update your permission to access to framework etc.

Just reply in here for leaving me any messages
Also please don't close this issue

Regards
szl.kiev

**Comment by ExPeacer** [comment]
Can I close it? :D
By the way, if you wanna test something, send me a message, I'll complie it for you, and I'll upload it to my FTP server, and you can download it anytime/anywhere.

**Comment by szlkiev** [comment]
Especially you long gone Mister :) you the one who provoked me with this github thing, do your magic again will ya :)

**Comment by championswimmer** [comment]
you take care of yourself... and there are a lot of nice people who'll in the mean time take care of PAC-man :)

**Comment by ExPeacer** [comment]
Yeah, I rerolled to another device, you know :) I'm still get notifications to my mail, so I'm checking always the things from background :)

**Comment by szlkiev** [comment]
Yes champ, i count on you too bro.
Xp, your another device is craving for pacman too,  isn't it :)

**Comment by championswimmer** [comment]
yeah... Xperia S and V will soon rock PAC 4.2.2 :) don't worry about that

# mate

catch me on http://championswimmer.tk

**Comment by ExPeacer** [comment]
My new device can't get any source-based ROM - now :)
CM don't like Intel Atom x86 based devices...

**Comment by OldDroid** [comment]
well szlkiev, next 3 days is study time for my exams after that i will contact you at gtalk ;-)

**Comment by bluefa1con** [comment]
we got you covered :)

**Comment by szlkiev** [comment]
Nice :)

**Comment by cmartinbaughman** [comment]
Should I just keep making push requests or what to make some contributions cause I have a few in my queue that I didn't get to send yet? Thanks!

**Comment by szlkiev** [comment]
Added :)

**Comment by cmartinbaughman** [comment]
Cool thank you sir! I'll try to help cover you as well!

**Comment by Druboo666** [comment]
will try to help whenever i can
this one i cant leave :)

**Comment by singhdd93** [comment]
i am loving this project
contributing my bit
