### ISSUE TITLE
Repo Sync Errors on the cm-10.2 branch

### ISSUE THREAD

**Issue by duffieldj1** [PAC-ROM/pac-rom#29]
[default.xml.zip With organized changes](https://github.com/PAC-ROM/pac-rom/files/70774/default.xml.zip)

android_packages_apps_PackageInstaller
android_packages_providers_ContactsProvider

The repos above do not have a cm-10.2 branch on pac remote. Request to change the remote for those repos to cm. Also I think there are more like that as well but I wont know until my repo sync is complete.

|EDIT|
HALO - Request to change remote to pa and revision to jb43
android_packages_apps_Dialer - Request to change remote to cm

Lastly android_external_svox the remote needs to be from AOSP as Cyanogen's repository has been shut down.

Thanks
Jeremy Duffield

**Comment by duffieldj1** [comment]
PAC-ROM 4.3.1 is my favorite version and builds no longer exist for grouper

**Comment by Nick0703** [comment]
I'll fix it next week.
